### ISSUE TITLE
How to generate python.zip?

### ISSUE THREAD

**Issue by MartinPham** [vapormusic/mangareader-qtpy#2]
Hi there, thanks for your awesome reader!
Just a question: How could I build the libraries (Qt,.. etc) as you did in the python.zip? I'd like to port it into older Kindle (K2), tried to use the crosschain env but no luck.. Could you please guide me a bit?

Thanks!

**Comment by tva2000hn** [comment]
Hmm i dont build the Qt libraries myself, most of them are from https://github.com/fperdigon/kindle_Python_PyQt_env. Armel debian jessie build should be working for kindle.

**Comment by MartinPham** [comment]
thank you!
